module.exports = {
    menu: [
        {name: "KUPON", ru: "КУПОНЫ"},
        {name: "RUB", ru: "руб."},
        {name: "YOUR_ORDER", ru: "Ваш заказ"},
        {name: "CANCEL", ru: "ОТМЕНА"},
        {name: "GO_TO_CART", ru: "Перейти к оформлению"},
        {name: "SELECT_ALL", ru: "Выберите все"},
        {name: "COMPLECT_POSITIONS", ru: "позиции набора"},
        {name: "YOUR", ru: "Ваш"},
        {name: "BACK", ru: "Передумал"},
        {name: "NOT_ALL_POSITIONS", ru: "Вы выбрали не все позиции"},
        {name: "CONTINUE_SELECTION", ru: "Продолжить выбор"},
        {name: "ENTER_COUPON_NUMBER", ru: "Введите номер купона"},
        {name: "SELECT_ORDER_OPTION", ru: "ВЫБЕРЕТЕ ОПЦИЮ ЗАКАЗА"},
        {name: "IMG_OUT", ru: "out.jpg"},
        {name: "IMG_HERE", ru: "here.jpg"},
        {name: "CART", ru: "КОРЗИНА"},
        {name: "ORDER_SUM", ru: "Сумма вашего заказа"},
        {name: "PAY", ru: "ОПЛАТИТЬ"},
        {name: "BACK_TO_MENU", ru: "Назад в меню"},
        {name: "ORDER_NUMBER", ru: "Заказ номер"},
        {name: "PAYING", ru: "Организуем процедуру оплаты"},
        {name: "CLOSE", ru: "Закрыть"},
        {name: "OK", ru: "OK"},
        {name: "HELPER", ru: "ВМЕСТЕ ВКУСНЕЕ!"},
        {name: "DO_NOT_FORGET_EXTRAS", ru: "Не забудьте взять дополнение к вашему блюду"},
        {name: "WAIT_FOR_ORDER", ru: "Ожидайте заказ в зоне выдачи..."},
        {name: "BOARDING_PASS_NUMBER", ru: "ПОСАДОЧНЫЙ ТАЛОН №:"},
    ]
}